### ISSUE TITLE
Add/modify Cycler Station view

### ISSUE THREAD

**Issue by mariuscrsn** [WattRex/Battery-Experiments-Manager#1]
Design and implement a new view that enables the user to register or modify a cycling station.
First, the user must select or insert information related to the computational unit (Port, IP, User, Password, Hostname...).
Next, the available devices are listed, and the user can configure the cycling station. For each selected device, the user can also configure monitored measurements and change names of each magnitude.

- [x] Mockup
- [x] Implement view for CU
- [x] Implement View for CS with available devices
- [x] Integrate with detector
- [x] Implement Name change feature

**Comment by mariuscrsn** [comment]
Not allow to modify cycler station if there are any experiment not ended.

**Comment by javibu13** [comment]
> Not allow to modify cycler station if there are any experiment not ended.

Not necessary
