### ISSUE TITLE
Master DB changes

### ISSUE THREAD

**Issue by mariuscrsn** [WattRex/Battery-Experiments-Manager#2]
- [x] Change name of DB to `wattrex_master_db`
- [x] Check changes on doc vs cache and master db
- [x] Apply minimum privileges for each user
- [x] Prepare devops environments: `development`, `stagging` and `production`
- [x] #3
- [x] Add Power on generic measures

**Comment by mariuscrsn** [comment]
- [ ] Add table of LinkConfiguration (master db and drv-db)

**Comment by RobertoAldea** [comment]
> * [ ]  Add table of LinkConfiguration (master db and drv-db)
Code to create the table in sql
```
create table if not exists LinkConfiguration
(
    CompDevID       MEDIUMINT       UNSIGNED    not null,
    Property        VARCHAR(30) NOT NULL,
    Value        	  VARCHAR(30) NOT NULL,

    constraint LinkConfiguration_pk_1
        primary key (CompDevID),
    constraint LinkConfiguration_fk_1
        foreign key (CompDevID) references CompatibleDevices (CompDevID)
);
```

**Comment by mariuscrsn** [comment]
- [ ] Add used and available measures tables
