### ISSUE TITLE
Change Name field by SN

### ISSUE THREAD

**Issue by pastorpflores** [WattRex/Battery-Experiments-Manager#38]
Please assume the only unique field is SN. Battery name should be use to introduce the commercial name of the cell, but when creating a new experiment or reviewing them, the desired field is SN.

Proposed changes:

1.  Add a column "SN" after ID and before Name in the experiments window
2.  Change the selectable field "Battery" for "Battery SN" in Add experiment window

Thanks :)

**Comment by javibu13** [comment]
2. Change the selectable field "Battery" for "Battery SN" in Add experiment window
![image](https://github.com/WattRex/Battery-Experiments-Manager/assets/120368047/43de46b5-8ccd-47d9-aeb6-58810a09c88f)
You can write the name of your battery to filter among the serial numbers 🔋 💥

**Comment by javibu13** [comment]
Add a column "SN" after ID and before Name in the experiments window
![image](https://github.com/WattRex/Battery-Experiments-Manager/assets/120368047/7bee7399-eff1-4d12-8aa0-4fd734c34776)
